name: SAST

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sast:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run semgrep
        run: semgrep --config "p/react" --json -o semgrep-results.json . || true

      - name: Install project dependencies
        run: |
          npm ci

      - name: Build project
        run: |
          npm run build --if-present

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            semgrep-results.json
