name: SCA scan

on:
  push:
    branches: [ main, nam01 ]
  workflow_dispatch: 

jobs:
  dep-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Scan dependencies
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --json-file-output=snyk-results.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dep-scan-reports
          path: |
            snyk-results.json
